SELECT * FROM (
SELECT A.REST_ID , A.REST_NAME AS REST_NAME , A.FOOD_TYPE AS FOOD_TYPE,
A.FAVORITES AS FAVORITES , A.ADDRESS AS ADDRESS , ROUND(AVG(B.REVIEW_SCORE),2) AS SCORE
FROM REST_INFO A LEFT JOIN 
REST_REVIEW B 
ON A.REST_ID = B.REST_ID
GROUP BY A.REST_ID , A.REST_NAME , A.FOOD_TYPE , A.FAVORITES , A.ADDRESS
HAVING A.address LIKE '서울%' 
ORDER BY ROUND(AVG(B.REVIEW_SCORE),2) DESC , A.FAVORITES DESC)
WHERE SCORE IS NOT NULL